name: idle_detector
description: "Detects when a user stops interacting with the app."
version: 0.9.0
homepage: https://github.com/sharpsan/idle_detector

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

# The following section is specific to Flutter packages.
flutter:
